(()=>{
const SIZE=50, s={before:null,records:[],role:'all',dates:new Map(),month:null,mode:'latest',total:null};
const T=document.querySelector('#timeline'),S=document.querySelector('#status'),O=document.querySelector('#older'),N=document.querySelector('#latest'),P=document.querySelector('#card'),D=document.querySelector('#day'),G=document.querySelector('#calendar-months'),H=document.querySelector('#month-title'),K=document.querySelector('#calendar-count'),Q=document.querySelector('#search-q'),X=document.querySelector('#search-clear'),Dialog=document.querySelector('#delete-dialog');
const L={user:'用户',assistant:'助手',event:'事件'},Z={unknown:'未标记来源',automation:'自动事件',reading:'阅读',web:'网页',mobile:'移动端'};let deleting=null;
const dateKey=v=>{let d=new Date(v);return isNaN(d)?String(v).slice(0,10):`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
const time=v=>{let d=new Date(v);return isNaN(d)?v:new Intl.DateTimeFormat('zh-CN',{hour:'2-digit',minute:'2-digit',hour12:false}).format(d)};
const dayLabel=v=>dateKey(v)===dateKey(new Date())?'今天':dateKey(v);
async function api(url,options){let r=await fetch(url,options);if(!r.ok)throw Error(`请求失败（${r.status}）`);return r.json()}
function visible(){return s.records.filter(r=>s.role==='all'||(s.role==='favorite'?!!r.favorite:r.role===s.role))}
function statusSuffix(count){if(s.mode==='search')return ` · 找到 ${s.total??count} 条`;if(s.mode==='day')return ` · 当天共 ${s.total??count} 条`;if(s.mode==='latest'&&s.dates.has(dateKey(new Date())))return ` · 今天共 ${s.dates.get(dateKey(new Date()))} 条`;return ''}
function draw(){T.replaceChildren();let rows=visible(),last='';for(const r of rows){let k=dateKey(r.created_at);if(k!==last){last=k;let d=D.content.firstElementChild.cloneNode(true);d.querySelector('time').textContent=dayLabel(r.created_at);T.append(d)}let n=P.content.firstElementChild.cloneNode(true);n.classList.add(r.role||'event');n.querySelector('.role').textContent=L[r.role]||'记录';n.querySelector('.source').textContent=Z[r.source]||r.source||'未标记窗口';n.querySelector('time').textContent=time(r.created_at);n.querySelector('.seq').textContent='#'+r.sequence;n.querySelector('.content').textContent=r.content;let f=n.querySelector('.favorite'),del=n.querySelector('.delete');f.textContent=r.favorite?'★':'☆';f.classList.toggle('on',!!r.favorite);f.onclick=()=>toggleFavorite(r);del.onclick=()=>{deleting=r;Dialog.showModal()};let actions=document.createElement('div');actions.className='record-actions';actions.setAttribute('aria-label','记录操作');actions.append(f,del);n.append(actions);T.append(n)}S.textContent=rows.length?`已展开 ${rows.length} 条记录${statusSuffix(rows.length)}${s.role!=='all'?' · 当前筛选':''}`:'没有找到记录';O.hidden=s.mode!=='latest'||!s.before}
async function latest(more=false){let url='/timeline/api/records?limit='+SIZE+(more&&s.before?'&before='+s.before:'');let d=await api(url);let a=(d.records||[]).reverse();s.records=more?[...s.records,...a]:a;s.before=d.next_before??null;s.mode='latest';s.total=null;draw()}
async function choose(day){S.textContent=`正在打开 ${day} 的记录…`;let d=await api('/timeline/api/day?date='+day+'&limit=50');s.records=(d.records||[]).reverse();s.before=null;s.mode='day';s.total=s.dates.get(day)??s.records.length;draw();scrollTo({top:T.offsetTop-10,behavior:'smooth'})}
async function search(q){let d=await api('/timeline/api/search?q='+encodeURIComponent(q)+'&limit=100');s.records=d.records||[];s.before=null;s.mode='search';s.total=s.records.length;draw()}
async function toggleFavorite(r){try{let d=await api('/timeline/api/records/'+r.id+'/favorite',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({favorite:!r.favorite})});r.favorite=d.favorite;draw()}catch(e){S.textContent='收藏操作失败，请稍后重试'}}
async function calendar(){let d=await api('/timeline/api/dates');s.dates=new Map((d.dates||[]).map(x=>[x.day,x.count]));if(!s.month&&d.dates?.length){let [y,m]=d.dates[0].day.slice(0,7).split('-').map(Number);s.month=new Date(y,m-1,1)}K.textContent=`${(d.dates||[]).length} 个有记录的日子`;month()}
function month(){if(!s.month)return;G.replaceChildren();let y=s.month.getFullYear(),m=s.month.getMonth(),first=new Date(y,m,1),days=new Date(y,m+1,0).getDate();H.textContent=`${y}年${m+1}月`;for(let i=0;i<first.getDay();i++){let b=document.createElement('i');b.className='blank';G.append(b)}for(let d=1;d<=days;d++){let day=`${y}-${String(m+1).padStart(2,'0')}-${String(d).padStart(2,'0')}`,count=s.dates.get(day),b=document.createElement('button');b.textContent=d;if(count){b.classList.add('has-record');let n=document.createElement('span');n.className='day-count';n.textContent=count;b.append(n);b.onclick=()=>choose(day)}G.append(b)}}
document.querySelector('#month-prev').onclick=()=>{s.month.setMonth(s.month.getMonth()-1);month()};document.querySelector('#month-next').onclick=()=>{s.month.setMonth(s.month.getMonth()+1);month()};
document.querySelectorAll('[data-role]').forEach(b=>b.onclick=async()=>{let wasFavorites=s.mode==='favorites';s.role=b.dataset.role;document.querySelectorAll('[data-role]').forEach(x=>x.classList.toggle('active',x===b));if(s.role==='favorite'){try{let d=await api('/timeline/api/favorites?limit=500');s.records=d.records||[];s.before=null;s.mode='favorites'}catch{S.textContent='收藏暂时无法读取';return}}else if(wasFavorites){await latest()}draw()});
document.querySelector('#search').onsubmit=e=>{e.preventDefault();let q=Q.value.trim();if(q){X.hidden=false;search(q)}};X.onclick=()=>{Q.value='';X.hidden=true;latest()};O.onclick=()=>latest(true);N.onclick=()=>scrollTo({top:0,behavior:'smooth'});addEventListener('scroll',()=>N.hidden=scrollY<550,{passive:true});
document.querySelector('#delete-confirm').onclick=async e=>{e.preventDefault();if(!deleting)return;try{await api('/timeline/api/records/'+deleting.id,{method:'DELETE'});s.records=s.records.filter(r=>r.id!==deleting.id);deleting=null;Dialog.close();await calendar();draw()}catch{deleting=null;Dialog.close();S.textContent='删除失败，请稍后重试'}};
let floating=document.querySelector('#floating-controls');if(floating&&typeof floating.showPopover==='function'&&!floating.matches(':popover-open'))floating.showPopover();calendar().then(()=>latest()).catch(()=>S.textContent='时间线暂时无法读取')})();